---
- name: Install Chrony
  apt:
    name: chrony
    state: latest
  tags: install-chrony

- name: Edit chrony conf NTP Server - other nodes
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: server controller iburst
  when: "'node1' not in inventory_hostname"
  tags: chrony-conf-controller

- name: Edit chrony conf allow conection other nodes - controller
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: allow {{ network }}
  when: "'node1' in inventory_hostname"
  tags: chrony-conf-other

- name: Edit chrony conf reference controller node - Controller
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: server {{ NTP_SERVER }} iburst
  when: "'node1' in inventory_hostname"
  tags: chrony-conf-other

- name: Remove pool lines
  lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^pool'
    state: absent
  when: "'node1' not in inventory_hostname"
  tags: remove-pool

- name: Restart Chrony
  service:
    name: chrony
    state: restarted
    enabled: yes
  tags: restart chrony

...  
