---
- name: Add wallaby repository
  shell: add-apt-repository cloud-archive:wallaby -y
  tags: add-repo

- name: Install Nova Compute on controller node
  apt:
    name: nova-compute
    state: latest
  when: "'node1' in inventory_hostname"
  tags: install-nova-compute

- name: Install Python3 Openstack Client
  apt:
    name: python3-openstackclient
    state: latest
  when: "'node1' in inventory_hostname"
  tags: install-python3-openstackclient

...
