---
- name: Update environment
  apt:
    update_cache: yes
  tags: update

- name: Upgrade packages
  apt:
    name: "*"
    state: latest
  tags: upgrade

- name: Configure hostname - controller
  hostname:
    name: controller
  when: "'node1' in inventory_hostname"
  tags: hostname

- name: Configure hostname - compute
  hostname:
    name: compute1
  when: "'node2' in inventory_hostname"
  tags: hostname

- name: Configure hostname - block
  hostname:
    name: block1
  when: "'node3' in inventory_hostname"
  tags: hostname

- name: Configure hostname - object
  hostname:
    name: object1
  when: "'node4' in inventory_hostname"
  tags: hostname

...  
