---
- name: Create the nova_api database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nova_api
    state: present
    login_user: root
    login_password: "{{ db_root_pass }}"
  when: "'node1' in inventory_hostname"
  tags: create-nova-api-database

- name: Create the nova database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nova
    state: present
    login_user: root
    login_password: "{{ db_root_pass }}"
  when: "'node1' in inventory_hostname"
  tags: create-nova-database

- name: Create the nova_cell0 database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nova_cell0
    state: present
    login_user: root
    login_password: "{{ db_root_pass }}"
  when: "'node1' in inventory_hostname"
  tags: create-nova-cell0-database

- name: Grant proper access to the databases - localhost
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nova
    password: "{{ NOVA_DBPASS }}"
    state: present
    append_privs: yes
    priv: "{{item}}"
  with_items:
    - 'nova_api.*:ALL'
    - 'nova.*:ALL'
    - 'nova_cell0.*:ALL'
  when: "'node1' in inventory_hostname"
  tags: privileges-all-db

- name: Grant proper access to the databases - other hosts
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: nova
    password: "{{ NOVA_DBPASS }}"
    state: present
    host: '%'
    append_privs: yes
    priv: "{{item}}"
  with_items:
    - 'nova_api.*:ALL'
    - 'nova.*:ALL'
    - 'nova_cell0.*:ALL'
  when: "'node1' in inventory_hostname"
  tags: privileges-all-db

...  
