---
- name: Install ovn packages - controller
  apt:
    name:
      - ovn-central
      - ovn-host
      - ovn-docker
      - ovn-common
    state: latest
  when: "'node1' in inventory_hostname"
  tags: install-ovn-packages

- name: Start the OVS service - controller
  shell: '/usr/share/openvswitch/scripts/ovs-ctl start  --system-id="random"'
  when: "'node1' in inventory_hostname"
  tags: start-ovs-service

- name: Configure the ovsdb-server component - controller
  shell: ovn-nbctl set-connection ptcp:6641:{{ network }} -- set connection . inactivity_probe=60000
  when: "'node1' in inventory_hostname"
  tags: configure-ovsdb-server

- name: Configure the ovsdb-server component - controller
  shell: ovn-sbctl set-connection ptcp:6642:{{ network }} -- set connection . inactivity_probe=60000
  when: "'node1' in inventory_hostname"
  tags: configure-ovsdb-server

- name: Configure the ovsdb-server component - controller
  shell: ovs-appctl -t ovsdb-server ovsdb-server/add-remote ptcp:6640:{{ network }}
  when: "'node1' in inventory_hostname"
  tags: configure-ovsdb-server

- name: Start ovn-northd service - controller
  service:
    name: ovn-northd
    state: started
    enabled: yes
  when: "'node1' in inventory_hostname"
  tags: start-ovn-northd

- name: Enable the OVN layer-3 service - controller
  replace:
    path: /etc/neutron/neutron.conf
    regexp: 'service_plugins = router'
    replace: 'service_plugins = ovn-router'
  when: "'node1' in inventory_hostname"
  tags: enable-ovn-layer-3

- name: Configure ml2 section - controller
  replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: 'mechanism_drivers = linuxbridge,l2population'
    replace: 'mechanism_drivers = ovn'
  when: "'node1' in inventory_hostname"
  tags: conf-ml2-section

- name: Configure ml2 section - controller
  replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: 'type_drivers = flat,vlan,vxlan'
    replace: 'type_drivers = local,flat,vlan,geneve'
  when: "'node1' in inventory_hostname"
  tags: conf-ml2-section

- name: Configure ml2 section - controller
  replace:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: 'tenant_network_types = vxlan'
    replace: 'tenant_network_types = geneve'
  when: "'node1' in inventory_hostname"
  tags: conf-ml2-section

- name: Configure ml2 section - controller
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'overlay_ip_version = 4'
    insertafter: '^extension_drivers = port_security'
  when: "'node1' in inventory_hostname"
  tags: conf-ml2-section

- name: Configure the Geneve ID range and maximum header size - controller
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'vni_ranges = 1:65536'
    insertafter: '^\[ml2_type_geneve\]$'
  when: "'node1' in inventory_hostname"
  tags: conf-geneve-id

- name: Configure the Geneve ID range and maximum header size - controller
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'max_header_size = 38'
    insertafter: '^vni_ranges = 1:65536'
  when: "'node1' in inventory_hostname"
  tags: conf-geneve-id

- name: Enable support for VLAN provider and self-service networks on one or more physical networks - controller
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'network_vlan_ranges = {{ PROVIDER_INTERFACE_NAME }}:{{ MIN_VLAN_ID }}:{{ MAX_VLAN_ID }}'
    insertafter: '^\[ml2_type_vlan\]$'
  when: "'node1' in inventory_hostname"
  tags: enable-support-vlan-provider

- name: Enable security groups - controller
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'enable_security_group = true'
    insertafter: '^\[securitygroup\]$'
  when: "'node1' in inventory_hostname"
  tags: enable-support-vlan-provider

- name: Configure OVS database access and L3 scheduler - controller
  blockinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    block: |
      #
      [ovn]
      ovn_nb_connection = tcp:{{ ip_controller }}:6641
      ovn_sb_connection = tcp:{{ ip_controller }}:6642
      ovn_l3_scheduler = {{ OVN_L3_SCHEDULER }}
  when: "'node1' in inventory_hostname"
  tags: conf-ovs-db-access-and-scheduler

- name: ovn-cms-options - controller
  shell: 'ovs-vsctl set open . external-ids:ovn-cms-options=enable-chassis-as-gw'
  when: "'node1' in inventory_hostname"
  tags: ovn-cms-options

...  
