---
- name: Create the neutron user
  shell: 'openstack user create --domain default --password {{ NEUTRON_PASS }} neutron'
  when: "'node1' in inventory_hostname"
  tags: create-neutron-user

- name: Add the admin role to the neutron user
  shell: 'openstack role add --project service --user neutron admin'
  when: "'node1' in inventory_hostname"
  tags: user-role

- name: Create the neutron service entity
  shell: 'openstack service create --name neutron --description "OpenStack Networking" network'
  when: "'node1' in inventory_hostname"
  tags: create-neutron-service

- name: Create the Networking service API endpoints - public
  shell: 'openstack endpoint create --region RegionOne network public http://controller:9696'
  when: "'node1' in inventory_hostname"
  tags: api-endpoints

- name: Create the Networking service API endpoints - internal
  shell: 'openstack endpoint create --region RegionOne network internal http://controller:9696'
  when: "'node1' in inventory_hostname"
  tags: api-endpoints

- name: Create the Networking service API endpoints - admin
  shell: 'openstack endpoint create --region RegionOne network admin http://controller:9696'
  when: "'node1' in inventory_hostname"
  tags: api-endpoints

...  
