---
## Nodes IPs
ip_controller: 172.31.92.40
ip_compute: 172.31.92.141
ip_block: 172.31.93.48
ip_object: 172.31.90.193

## Network
network: 172.31.0.0/16

## NTP Server
NTP_SERVER: localhost

## Passwords
db_root_pass: openstack
RABBIT_PASS: openstack
