---
## Nodes IPs
ip_controller: 10.0.80.40
ip_compute: 10.0.80.43
ip_block: 10.0.80.44
ip_object: 10.0.80.46

## Network
network: 10.0.0.0/16

## NTP Server
NTP_SERVER: localhost

## Passwords
db_root_pass: openstack
RABBIT_PASS: openstack
