---
- name: Edit apache conf file - ServerName
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: 'ServerName controller'
  when: "'node1' in inventory_hostname"
  notify:
    - Restart apache
  tags: apache-conf

...  
