---
- name: Create keystone database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: keystone
    state: present
    login_user: root
    login_password: "{{ db_root_pass }}"
  tags: keystone-database

- name: Grant all privileges on keystone database to keystone user - localhost
  mysql_user:
    name: keystone
    password: "{{ KEYSTONE_DBPASS }}"
    host: localhost
    state: present
    update_password: on_create
    priv: 'keystone.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: privileges-keystone-userdb

- name: Grant all privileges on keystone database to keystone user - any host
  mysql_user:
    name: keystone
    password: "{{ KEYSTONE_DBPASS }}"
    host_all: yes
    state: present
    priv: 'keystone.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags: privileges-keystone-userdb

...  
