---
- name: Create a cinder user
  shell: openstack user create --domain default --password {{ CINDER_PASS }} cinder
  when: "'node1' in inventory_hostname"
  tags: create-cinder-user

- name: Add the admin role to the cinder user
  shell: openstack role add --project service --user cinder admin
  when: "'node1' in inventory_hostname"
  tags: admin-role

- name: Create the cinderv2 service entitie
  shell: 'openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2'
  when: "'node1' in inventory_hostname"
  tags: create-service-entities

- name: Create the cinderv3 service entitie
  shell: 'openstack service create --name cinderv3 --description "OpenStack Block Storage" volumev3'
  when: "'node1' in inventory_hostname"
  tags: create-service-entities

- name: Create the Block Storage service API endpoints - volumev2 public
  shell: 'openstack endpoint create --region RegionOne volumev2 public http://controller:8776/v2/%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Block Storage service API endpoints - volumev2 internal
  shell: 'openstack endpoint create --region RegionOne volumev2 internal http://controller:8776/v2/%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Block Storage service API endpoints - volumev2 admin
  shell: 'openstack endpoint create --region RegionOne volumev2 admin http://controller:8776/v2/%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Block Storage service API endpoints - volumev3 public
  shell: 'openstack endpoint create --region RegionOne volumev3 public http://controller:8776/v3/%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Block Storage service API endpoints - volumev3 internal
  shell: 'openstack endpoint create --region RegionOne volumev3 internal http://controller:8776/v3/%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Block Storage service API endpoints - volumev3 admin
  shell: 'openstack endpoint create --region RegionOne volumev3 admin http://controller:8776/v3/%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

...
