--- # https://docs.openstack.org/install-guide/environment.html
- name: Configure environment
  hosts: 'all'
  become: yes
  become_method: sudo
  roles:
    - { role: prepare-environment, tags: ["prepare-environment"]}

...      
