--- # https://docs.openstack.org/install-guide
- name: Configure environment
  hosts: 'all'
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: prepare-environment, tags: ["prepare-environment"]}
    - { role: keystone, tags: ["keystone"]}
    - { role: horizon, tags: ["horizon"]}
    - { role: glance, tags: ["glance"]}
    - { role: placement, tags: ["placement"]}
    - { role: nova, tags: ["nova"]}
    - { role: neutron, tags: ["neutron"]}
    - { role: cinder, tags: ["cinder"]}
    - { role: swift, tags: ["swift"]}

...      
