---
- name: Create the glance user
  shell: openstack user create --domain default --password {{ GLANCE_PASS }} glance
  when: "'node1' in inventory_hostname"
  tags: create-glance-user

- name: Add the admin role to the glance user and service project
  shell: openstack role add --project service --user glance admin
  when: "'node1' in inventory_hostname"
  tags: admin-role

- name: Create the glance service entity
  shell: openstack service create --name glance --description "OpenStack Image" image
  when: "'node1' in inventory_hostname"
  tags: create-glance-service

- name: Create the Image service API endpoints - public
  shell: openstack endpoint create --region RegionOne image public http://controller:9292
  when: "'node1' in inventory_hostname"
  tags: create-image-apt-end

- name: Create the Image service API endpoints - internal
  shell: openstack endpoint create --region RegionOne image internal http://controller:9292
  when: "'node1' in inventory_hostname"
  tags: create-image-apt-end

...
