---
- name: Create images directory
  file:
    path: /root/images
    state: directory
  tags: create-images-dir

- name: Get cirros image
  get_url:
    url: http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
    dest: /root/images/
  tags: get-cirros-image

- name: Upload the image to the Image service using the QCOW2, bare and container format
  shell: 'glance image-create --name "cirros" --file /root/images/cirros-0.4.0-x86_64-disk.img --disk-format qcow2 --container-format bare --visibility=public'
  tags: upload-image

- name: List images
  shell: glance image-list
  tags: list-images

...
