---
- name: Create the swift user
  shell: 'openstack user create --domain default --password {{ SWIFT_PASS }} swift'
  when: "'node1' in inventory_hostname"
  tags: create-swift-user

- name: Add the admin role to the swift user
  shell: 'openstack role add --project service --user swift admin'
  when: "'node1' in inventory_hostname"
  tags: add-admin-role

- name: Create the swift service entity
  shell: 'openstack service create --name swift --description "OpenStack Object Storage" object-store'
  when: "'node1' in inventory_hostname"
  tags: create-swift-entity

- name: Create the Object Storage service API endpoints - public
  shell: 'openstack endpoint create --region RegionOne object-store public http://controller:8080/v1/AUTH_%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Object Storage service API endpoints - internal
  shell: 'openstack endpoint create --region RegionOne object-store internal http://controller:8080/v1/AUTH_%\(project_id\)s'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

- name: Create the Object Storage service API endpoints - admin
  shell: 'openstack endpoint create --region RegionOne object-store admin http://controller:8080/v1'
  when: "'node1' in inventory_hostname"
  tags: create-endpoints

...  
