---
- name: Show the service status
  shell: 'swift stat'
  when: "'node1' in inventory_hostname"
  tags: show-service-status

- name: Create container1 container
  shell: 'openstack container create container1'
  when: "'node1' in inventory_hostname"
  tags: create-container

- name: Create teste file
  file:
    path: /tmp/test-container
    state: touch
  when: "'node1' in inventory_hostname"
  tags: create-test-file

- name: Upload a test file to the container1 container
  shell: 'openstack object create container1 /tmp/test-container'
  when: "'node1' in inventory_hostname"
  tags: upload-test-file

- name: List files in the container1 container
  shell: 'openstack object list container1'
  when: "'node1' in inventory_hostname"
  tags: list-files-container1

...  
